sticker_id = [

    "CAACAgQAAxkBAAEGjG1mgc4V-8IhxCdZa9loZD4QvWvBOwACkQAD6AoxLX2YrjAGFrsdNQQ",
    "CAACAgQAAxkBAAEGjHtmgdA1NPRfRNZ29-AXIzsoXtGhvwAC3wAD6AoxLaFydc0Ry1PZNQQ",
    "CAACAgQAAxkBAAEGjH1mgdBGNIjg0VGmNasPTrLjNbgSbQACoQAD6AoxLda21Pb6nXUhNQQ",
    "CAACAgQAAxkBAAEGjH9mgdBeFWGT5gPIKHiQljCu6xH9KwACDQEAAugKMS2-cOnVcS_CqzUE",
    "CAACAgQAAxkBAAEGjIFmgdBsPkl5PEpgWNocu_NACYa7-wAClgAD6AoxLTiZeG3QlxZsNQQ",
    "CAACAgQAAxkBAAEGjItmgdJCb2JxiwifK1Y3wTFIekZBEQACmAAD6AoxLRHhZyjkq0glNQQ",
    "CAACAgIAAxkBAAEGjI1mgdJcNf7gukmedagVzASjrf6nYAAC6koAAuCjggcjPrpyUZMvHTUE",
    "CAACAgQAAxkBAAEGjJFmgdJyCzsrnugLKz8bVDRCc1E9jgACIAEAAugKMS3A7FLbLkG2-jUE",
    "CAACAgIAAxkBAAEGjJNmgdKFv_AvPoWT94OLKCPAoSaWaAAC3EoAAuCjggcGhJakIfl2MTUE",
    "CAACAgQAAxkBAAEGjJVmgdK1JPtaA4aWHLr9JqJaSMHIugACiwAD6AoxLVIiI5tFDHEVNQQ"

]
